services:
  db:
    ports:
      - "5432:5432"
  
  web:
    command: >
      bash -lc "uvicorn src.dashboard.app:create_app --host 0.0.0.0 --port 8000 --reload \
      --reload-dir /app/src \
      --reload-include '*.py' \
      --factory \
      --log-config=null"
    environment:
      DASHBOARD_DEBUG: "1"
      # Development logging configuration
      LOG_LEVEL: "DEBUG"
      LOG_DIR: "/app/logs"

  agent:
    # Enable code reload in development mode
    command: bash -lc "python -m agent --gpu-index $$GPU_INDEX --reload"
    environment:
      # Development logging configuration
      LOG_LEVEL: "DEBUG"
      LOG_DIR: "/app/logs"
      ENVIRONMENT: "development"

  ui:
    command: sh -lc "npm install && npm run dev -- -p 3000"

  nginx:
    image: nginx:alpine
    container_name: dashboard-nginx
    depends_on:
      - ui
      - web
    volumes:
      - ./deploy/nginx/ui.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
