services:
  db:
    ports:
      - "5432:5432"
  
  web:
    command: >
      bash -lc "pip install --no-cache-dir -r src/dashboard/requirements.txt && \
      uvicorn src.dashboard.app:app --host 0.0.0.0 --port 8000 --reload \
      --reload-dir /app/src \
      --reload-include '*.py' --reload-include '*.html' --reload-include '*.css' --reload-include '*.js' \
      --log-level debug"
    environment:
      DASHBOARD_DEBUG: "1"

  agent:
    # Enable code reload for faster iteration during development
    command: bash -lc "python -m agent.server --gpu-index $$GPU_INDEX --reload"
